### ISSUE TITLE
Uniswap USD price sometimes gets set to 0

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/uniswap-subgraph#14]
https://github.com/graphprotocol/uniswap-subgraph/blob/edcf0b2a45fffa52bdbdb9bab124d4d8484ccf19/src/mappings/exchange.ts#L152-L155

https://github.com/graphprotocol/uniswap-subgraph/blob/edcf0b2a45fffa52bdbdb9bab124d4d8484ccf19/src/mappings/exchange.ts#L365-L368

Both of these can cause the price to go to 0. Basically, a brand new exchange, or an exchange that has a very very small token price, can result in this number being 0. It will then change its value the next time any token or eth is purchased. 

This needs to just work better. I have some ideas that hopefully I can get to next week

**Comment by ianlapham** [comment]
This may have to with a decimal issue for new exchanges. Right now on the subgraph we set the decimal value to 0 if there is so preset found (see factory.ts)

<img width="631" alt="Screen Shot 2019-09-04 at 4 22 02 PM" src="https://user-images.githubusercontent.com/17100331/64288509-4ab0ee80-cf30-11e9-978b-27b3911c28a2.png">

But if we query an exchange with a known null value (DGX) it returns 0 

<img width="1717" alt="Screen Shot 2019-09-04 at 3 55 02 PM" src="https://user-images.githubusercontent.com/17100331/64288462-281ed580-cf30-11e9-96e9-69142d34f0ab.png">
