### ISSUE TITLE
Exchange is not set for UserExchangeData entries

### ISSUE THREAD

**Issue by Destiner** [graphprotocol/uniswap-subgraph#19]
When trying to query the exchange data on user uniToken balances, the query throws "entry is null" error. Here's a query to reproduce:

```graphql
{
  userExchangeDatas(where: {
    userAddress: "0x46499275b5c4d67dfa46B92D89aADA3158ea392e",
    uniTokenBalance_gt: 0
  }) {
    uniTokenBalance
    exchangeAddress
    exchange {
      id
    }
  }
}
```

I think this is due to `exchange` field [not set](https://github.com/graphprotocol/uniswap-subgraph/blob/master/src/mappings/exchange.ts#L37) during UserExchangeData entry creation.

**Comment by davekaj** [comment]
I submitted a fix and pushed an updated uniswap subgraph to the hosted service

https://github.com/graphprotocol/uniswap-subgraph/commit/6817e74f6c2b3832d90e420c109ad7a203b309f4

https://thegraph.com/explorer/subgraph/graphprotocol/uniswap?version=pending

It will take the pending version a few days to sync fully
