### ISSUE TITLE
WS subscriptions seem to be not working

### ISSUE THREAD

**Issue by Mingela** [graphprotocol/uniswap-subgraph#32]
Hello!
I'm very glad to have an opportunity to use thegraph as a source of data for Uniswap. I succeeded in using HTTP queries following the guide and the playground at https://thegraph.com/explorer/subgraph/graphprotocol/uniswap
Example:
```
Request
{
  "query" : "
    { exchanges(where: {tokenAddress: \"0x6b175474e89094c44da98b954eedeac495271d0f\"}) 
      { tokenAddress tokenSymbol startTime price priceUSD } 
    }
  "
}

Response
{"data":{ "exchanges": 
 [{"price":"137.235425158258860500","priceUSD":"1.007148187411886213892813100555711444280861568563425025772874606616100759801755264482597497036750276","startTime":1573833929,"tokenAddress":"0x6b175474e89094c44da98b954eedeac495271d0f","tokenSymbol":"DAI"}]}}
```

Now I want my application to listen for live exchanges updates (price changes). There is a `subscription` in GraphQL to do so but I couldn't handle using websocket api. For example an external playground (https://www.websocket.org/echo.html) is unable to connect to wss://api.thegraph.com/subgraphs/name/graphprotocol/uniswap. Is it currently enabled? Could you please provide any details on how it should be used so far (ideally extending the playground with subscriptions)? I do not really want to go deeper into GraphQL related client libraries for now, just want to try out simple 'native' ws tools as I've done with the http query.
So I'd like to be able perform something like
```
Request
{
  "subscription" : "
    { exchanges(where: {tokenAddress: \"0x6b175474e89094c44da98b954eedeac495271d0f\"}) 
      { tokenAddress tokenSymbol startTime price priceUSD } 
    }
  "
}
```
using websocket.

Thank you. Couldn't find any less formal channel for communications.

UPD:
Actually it seems that connection could be acquired through my application, but no messages are being transmitted and the WS client receives 'Connection closed' after 5 minutes.
I just connect to wss://api.thegraph.com/subgraphs/name/graphprotocol/uniswap then subscribe to it and send a message from the snippet above.

**Comment by davekaj** [comment]
Hey @Mingela , the best place to talk about this would be our discord in the #support  channel

You can join by following this link https://discord.gg/qndxBm

**Comment by Mingela** [comment]
@davekaj Thank you! I got help there, unfortunately I couldn't finish with a plain websocket. I used apollo library to generate interaction wrappers.

Btw how to request new token to appear in the subgraph?
